import { useState, useEffect } from "react";
import Head from "next/head";
import {
  Background,
  NavBar,
  PageContent,
  LoadingScreen,
} from "~/components/lib";

export default function Home() {
  const [stars, setStars] = useState(0);
  const [version, setVersion] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchGithubStars() {
      try {
        const resGithub = await fetch(
          "https://api.github.com/repos/JohnVersus/nimbleuikit"
        );
        const dataGithub = await resGithub.json();
        setStars(dataGithub.stargazers_count);
      } catch (error) {
        console.log(error);
      }
    }

    async function fetchVersion() {
      try {
        const resNpm = await fetch(
          "https://registry.npmjs.org/@nimbleuikit/atoms"
        );
        const dataNpm = await resNpm.json();
        setVersion(dataNpm["dist-tags"].latest);
      } catch (error) {
        console.log(error);
      }
    }

    fetchGithubStars();
    fetchVersion();
  }, []);

  useEffect(() => {
    if (version && stars) setLoading(false);
  }, [version, stars]);

  if (loading) {
    return <LoadingScreen />;
  }

  return (
    <>
      <Head>
        <title>Nimble UI kit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Background>
        <NavBar />
        <PageContent version={version} stars={stars} />
      </Background>
    </>
  );
}
