name: Publish Packages

on:
  push:
    branches:
      - main

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          # This makes action fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

        #Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.15.0

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install
        run: pnpm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm run build
        working-directory: ./packages/atoms

      - name: Publish Atoms
        uses: changesets/action@v1
        with:
          publish: cd packages/atoms && pnpm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
