on:
  push:
    branches:
      - main
    paths:
      - "docs/*.mdx"
      - "packages/**"
      # - ".github/workflows/storybook.yml"

name: Publish storybook

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: pnpm install

      - name: Install nimble
        run: pnpm install @nimbleuikit/atoms@latest

      - name: Install Github Pages
        run: pnpm add -Dw gh-pages

      - name: Run tests
        run: pnpm run test

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
